# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "gatekeeper-addons"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/gatekeeper-addons"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "*/fixtures/**/*.dat",
  "*/fixtures/**/*.json",
  "*/fixtures/**/*.yaml",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/NYTimes/gziphandler/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gofrs/uuid/v5/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/google/go-containerregistry/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gophercloud/gophercloud/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/gorilla/mux/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/mitchellh/mapstructure/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/pkg/errors/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_golang/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-bits/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.uber.org/automaxprocs/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.xyrillian.de/schwift/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/apimachinery/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/client-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/beorn7/perks/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cespare/xxhash/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/containerd/stargz-snapshotter/estargz/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/docker/cli/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/docker/docker-credential-helpers/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/emicklei/go-restful/v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/fxamacker/cbor/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-logr/logr/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonpointer/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonreference/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-task/slim-sprig/v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/gogo/protobuf/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/gnostic-models/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/pprof/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/uuid/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/golang-lru/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/itchyny/gojq/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/itchyny/timefmt-go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/josharian/intern/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/jpillora/longestcommon/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/json-iterator/go/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/kr/pretty/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kr/text/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kylelemons/godebug/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/mailru/easyjson/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/majewsky/gg/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/mitchellh/go-homedir/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/modern-go/concurrent/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/modern-go/reflect2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/munnerz/goautoneg/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/onsi/ginkgo/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/onsi/gomega/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/go-digest/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/image-spec/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/prashantv/gostub/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_model/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/common/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/procfs/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/rogpeppe/go-internal/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/sergi/go-diff/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/sirupsen/logrus/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/spf13/pflag/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/stretchr/objx/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/vbatts/tar-split/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/x448/float16/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/goleak/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.yaml.in/yaml/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/golang.org/x/net/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/oauth2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sync/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sys/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/term/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/text/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/time/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/tools/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/google.golang.org/protobuf/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/check.v1/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/evanphx/json-patch.v4/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/inf.v0/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/gotest.tools/v3/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/api/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/klog/v2/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/kube-openapi/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/utils/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/json/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/randfill/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/structured-merge-diff/v4/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/yaml/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"
